package com.nvshen.chmp4;

import android.os.Binder;
import android.os.IBinder;
import android.os.Parcel;
import android.util.Log;

import java.lang.reflect.Method;

/**
 * ServiceManager (class k) - FULLY RESTORED FROM nmmp BYTECODE
 * Singleton Binder Service Manager for daemon IPC
 *
 * Manages the Binder IPC connection between the app and the daemon/hook.
 * Creates and registers a BinderService (class i) as a system service,
 * enabling cross-process communication with the injected hook in cameraserver.
 *
 * Transaction protocol (from binder_service.cpp):
 *   code 0: Register client binder - sends our binder to daemon
 *   code 1: License verification
 *   code 2: Sub-command dispatch (1=setVideoPath, 2=setFilter, 3=getFrame)
 *   code 3: test_setSwapJpegWH
 *   code 4: test_toggleCamera
 *   code 5: test_setHeightPadding
 */
public class k {

    private static final String TAG = "CHMP4";
    // LOGCAT CONFIRMED: demo uses dynamic service name (ABoTx5nBJ, AHVC1BQWL)
    // Generated by ApiManager and stored in SharedPreferences
    // Fallback to CHMP4PlayerService if not available

    private static k sInstance;           // f3528d
    private IBinder mRemoteBinder;        // f3529a
    private int mStatus = 0;             // f3530b
    i mLocalBinder = new i();            // f3531c - creates BinderService on init

    // ===== getInstance() - returns singleton ServiceManager =====
    static k c() {
        if (sInstance == null) {
            synchronized (k.class) {
                if (sInstance == null) {
                    sInstance = new k();
                    sInstance.a();
                }
            }
        }
        return sInstance;
    }

    /**
     * init() - registers Binder service with Android ServiceManager
     * BYTECODE [entry 32]: uses dynamic service name from ApiManager
     * LOGCAT CONFIRMED: demo logs "regCb 0" after registration
     */
    private void a() {
        try {
            String serviceName = com.nvshen.chmp4.d.B().getServiceName();
            Log.e(TAG, "a() registering service: " + serviceName);
            Class<?> sm = Class.forName("android.os.ServiceManager");
            Method addService = sm.getDeclaredMethod("addService", String.class, IBinder.class);
            addService.setAccessible(true);
            addService.invoke(null, serviceName, mLocalBinder);
            Log.e(TAG, "regCb " + serviceName + " OK");
        } catch (Exception ex) {
            Log.e(TAG, "regCb error:" + ex.getMessage(), ex);
        }
    }

    /**
     * refresh() / reconnect() - refreshes the Binder connection
     * BYTECODE [entry 34 b(), pc=54-64]:
     *   ApiManager.B() → getServiceName() → used as getService parameter
     * LOGCAT CONFIRMED: demo uses dynamic name (ABoTx5nBJ), not "CHMP4PlayerService"
     */
    public IBinder b() {
        try {
            Class<?> sm = Class.forName("android.os.ServiceManager");
            Method getService = sm.getDeclaredMethod("getService", String.class);
            getService.setAccessible(true);

            // BYTECODE [entry 34, pc=54-58]: ApiManager.B().p() → get service name
            String serviceName = com.nvshen.chmp4.d.B().getServiceName();

            mRemoteBinder = (IBinder) getService.invoke(null, serviceName);
            Log.e("HOOK", "binder = " + mRemoteBinder);
            Log.e("HOOK", "binder alive = " + (mRemoteBinder != null ? mRemoteBinder.isBinderAlive() : "null"));
            Log.e("HOOK", "localBinder = " + mLocalBinder);
            Log.e("HOOK", "thread = " + Thread.currentThread().getName());

            if (mRemoteBinder != null && mRemoteBinder.isBinderAlive()) {
                // Register our local binder with the daemon (transaction code 0)
                Parcel data = Parcel.obtain();
                Parcel reply = Parcel.obtain();
                data.writeStrongBinder(mLocalBinder);
                Log.e("HOOK", "transact(0) calling...");
                mRemoteBinder.transact(0, data, reply, 0);
                int status = reply.readInt();
                Log.e("HOOK", "transact(0) status=" + status);
                data.recycle();
                reply.recycle();
                mStatus = 1;
                Log.e("HOOK", "transact(0) done, mStatus=1");
            } else {
                mStatus = 0;
                Log.e("HOOK", "binder null or dead");
            }
        } catch (Exception ex) {
            Log.e(TAG, "service error: " + ex.getMessage(), ex);
            mStatus = 0;
        }
        return mRemoteBinder;
    }

    /**
     * getStatus() -> connection status via Binder transact
     * BYTECODE CONFIRMED [entry 37, 86 u16]:
     *   Parcel.writeInt x2 + IBinder.transact + Parcel.readInt
     *   + Log.d("A", "LL" + status + "/" + mStatus)
     */
    public int d() {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            return 0;
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeStrongBinder(mLocalBinder);
            mRemoteBinder.transact(0, data, reply, 0);
            int status = reply.readInt();
            Log.d("A", "LL" + status + "/" + mStatus);
            data.recycle();
            reply.recycle();
            return status;
        } catch (Exception ex) {
            return 0;
        }
    }

    /**
     * queryService(binder) -> service info string
     * Sends transaction code 0 to given binder and reads response
     */
    public String e(IBinder binder) {
        if (binder == null) return "";
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeStrongBinder(mLocalBinder);
            binder.transact(0, data, reply, 0);
            String result = reply.readString();
            data.recycle();
            reply.recycle();
            return result != null ? result : "";
        } catch (Exception ex) {
            Log.e(TAG, "queryService failed", ex);
            return "";
        }
    }

    /** cleanup() - unregisters Binder service */
    private void f() {
        try {
            Class<?> sm = Class.forName("android.os.ServiceManager");
            // There's no removeService in public API, just null the reference
            mRemoteBinder = null;
            mStatus = 0;
        } catch (Exception ex) {
            Log.e(TAG, "cleanup failed", ex);
        }
    }

    /**
     * sendCommand(command) -> response string
     * Sends a command string to the daemon via binder transaction code 2, sub-command 1
     * (setVideoPath)
     */
    public String g(String command) {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            Log.e(TAG, "binder send fail");
            return "";
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeInt(1); // sub-command 1 = setVideoPath
            data.writeString(command);
            mRemoteBinder.transact(2, data, reply, 0);
            int result = reply.readInt();
            data.recycle();
            reply.recycle();
            return String.valueOf(result);
        } catch (Exception ex) {
            Log.e(TAG, "sendCommand failed: " + ex.getMessage());
            return "";
        }
    }

    /**
     * queryValue(key) -> value string
     * Sends a query string via binder transaction code 2, sub-command 2 (setFilter)
     */
    public String h(String key) {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            return "";
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeInt(2); // sub-command 2 = setFilter
            data.writeString(key);
            mRemoteBinder.transact(2, data, reply, 0);
            int result = reply.readInt();
            data.recycle();
            reply.recycle();
            return String.valueOf(result);
        } catch (Exception ex) {
            Log.e(TAG, "queryValue failed", ex);
            return "";
        }
    }

    /**
     * transact(code) -> result int
     * Sends a direct transaction with given code to the remote binder
     */
    public int i(int transactionCode) {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            return -1;
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeInt(0);
            mRemoteBinder.transact(transactionCode, data, reply, 0);
            int result = reply.readInt();
            data.recycle();
            reply.recycle();
            return result;
        } catch (Exception ex) {
            Log.e(TAG, "transact failed: code=" + transactionCode, ex);
            return -1;
        }
    }

    /**
     * getTransactionName(code) -> name string
     * BYTECODE CONFIRMED [entry 29, 50 u16]:
     *   null check + b() + Parcel.writeInt + transact + Parcel.readInt
     *   + Integer.toString(result)
     *   NOT a hardcoded switch — queries daemon via Binder transact.
     */
    public String j(int transactionCode) {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            return "";
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeInt(transactionCode);
            mRemoteBinder.transact(transactionCode, data, reply, 0);
            int result = reply.readInt();
            data.recycle();
            reply.recycle();
            return String.valueOf(result);
        } catch (Exception ex) {
            return "";
        }
    }

    /**
     * getTransactionData(code) -> data string
     * Queries data for the given transaction code from the daemon
     */
    public String k(int transactionCode) {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            return "";
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeInt(transactionCode);
            mRemoteBinder.transact(transactionCode, data, reply, 0);
            String result = reply.readString();
            data.recycle();
            reply.recycle();
            return result != null ? result : "";
        } catch (Exception ex) {
            return "";
        }
    }

    /**
     * getConnectionCount() -> int
     * BYTECODE CONFIRMED [entry 31, 40 u16]:
     *   null check + b() + Parcel.obtain + writeInt + IBinder.transact
     *   + Parcel.readInt → return result
     *   NOT a simple mStatus return — queries via Binder transact.
     */
    public int l() {
        if (mRemoteBinder == null || !mRemoteBinder.isBinderAlive()) {
            return 0;
        }
        try {
            Parcel data = Parcel.obtain();
            Parcel reply = Parcel.obtain();
            data.writeStrongBinder(mLocalBinder);
            mRemoteBinder.transact(0, data, reply, 0);
            int result = reply.readInt();
            data.recycle();
            reply.recycle();
            return result;
        } catch (Exception ex) {
            return 0;
        }
    }
}
